pr:
- master

stages:
- stage: Compliance
  jobs:
  - job: 
    steps:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'

- stage: AccumuloSparkConnector
  jobs:
  - job:
    pool: 
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Maven@3
      displayName: 'Accumulo Spark Connector components'
      inputs:
        mavenPomFile: 'connector/pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
        options: '-B' # batch mode for non-interactive release

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: connector/iterator/target/microsoft-accumulo-spark-iterator-1.0.3-shaded.jar
        artifactName: accumulo-spark-iterator

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: connector/datasource/target/microsoft-accumulo-spark-datasource-1.0.3-shaded.jar
        artifactName: accumulo-spark-datasource

    - bash: cd connector/publish && ./publish.sh
      displayName: Publish to Sonatype
      condition: variables['ossrh_gpg']
      env:
        # these are credentials used to publish to oss.sonatype.org
        # credentials are stored as secrets in the build definition
        ossrh_gpg: $(ossrh_gpg)
        ossrh_username: $(ossrh_username)
        ossrh_password: $(ossrh_password)

